name: Sync SVN to GitHub

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-svn-to-github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SVN
        run: sudo apt-get install subversion

      - name: Make import.sh executable
        run: chmod +x ./.github/tools/import.sh

      - name: Sync SVN to GitHub
        run: |
          cd ./.github/tools
          ./import.sh

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --tags

      - name: Create Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEW_TAGS=$(git tag --points-at HEAD)
          for TAG in $NEW_TAGS
          do
            gh release create "$TAG" \
              --title "Release $TAG" \
              --notes "This is an automatic release created from SVN tag $TAG" \
              --generate-notes
          done
